version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 3          # <- default is 5
    groups:                              # <- group all github actions updates in a single PR
      development-dependencies:
        dependency-type: development
        patterns:
          - '*'

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 3
    groups:
      development-dependencies:
        dependency-type: development
        patterns:
          - "github.com/stretchr/testify"
      go-openapi-dependencies:
        dependency-type: production
        patterns:
          - "github.com/go-openapi/*"

